# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tesoro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
  pod 'Gifu'
  pod 'ImagePicker'
  pod 'PopupDialog'
  # Pods for Tesoro

end
